# Generated by Django 4.2 on 2025-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='category',
            field=models.CharField(choices=[('real', 'Real Pokémon'), ('virtual', 'Virtual Pokémon')], default='real', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
